services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    volumes:
      #- ./index.php:/var/www/html/index.php
      - .:/var/www/html/
      - ./images/:/var/www/html/images/
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data

  mysql:
    image: mariadb:10.8.3
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_tasklist_retriver
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_container
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db_data: